%YAML:1.0

# Sensor Data File for OpenCV

###
### Camera Parameters (cam 0)
###

# Camera general data
Camera.model: pinhole
Camera.fps: 20

# Camera calibration parameters
Camera.width: 640
Camera.height: 480

# Camera intrinsics (K)
Camera.fx: 517.306408
Camera.fy: 516.469215
Camera.cx: 318.643040
Camera.cy: 255.313989
#Camera.fx: 525.0
#Camera.fy: 525.0
#Camera.cx: 319.5
#Camera.cy: 239.5

# Camera distortion data
Camera.distortion_model: radial-tangential
Camera.k1: 0.262383
Camera.k2: -0.953104
Camera.p1: -0.005358
Camera.p2: 0.002628
Camera.k3: 1.163314
#Camera.k1: 0
#Camera.k2: 0
#Camera.p1: 0
#Camera.p2: 0
#Camera.k3: 0


###
### Feature Extraction Parameters ###
###

# Number of extracted features
Feature.nFeatures: 1000

# Scale factor of the image pyramid
Feature.scaleFactor: 2

# Number of octaves/levels of the image pyramid
Feature.nLevels: 3


###
### Misc ###
###