%YAML:1.0

# Sensor Data File for OpenCV

###
### Camera Parameters (cam 0)
###

# Camera general data
Camera.model: pinhole
Camera.fps: 20

# Camera calibration parameters
Camera.width: 640
Camera.height: 480

# Camera intrinsics (K)
#Camera.fx: 520.9
#Camera.fy: 521.0
#Camera.cx: 325.1
#Camera.cy: 249.7
Camera.fx: 525.0
Camera.fy: 525.0
Camera.cx: 319.5
Camera.cy: 239.5

# Camera distortion data
Camera.distortion_model: radial-tangential
#Camera.k1: 0.2312
#Camera.k2: -0.7849
#Camera.p1: -0.0033
#Camera.p2: -0.0001
#Camera.k3: 0.9172
Camera.k1: 0
Camera.k2: 0
Camera.p1: 0
Camera.p2: 0
Camera.k3: 0


###
### Feature Extraction Parameters ###
###

# Number of extracted features
Feature.nFeatures: 1000

# Scale factor of the image pyramid
Feature.scaleFactor: 2

# Number of octaves/levels of the image pyramid
Feature.nLevels: 5


###
### Misc ###
###